services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - menus_data:/var/lib/postgresql/data/
    env_file:
      - ../../.env

  redis:
    image: redis:latest
    ports:
      - $REDIS_PORT:$REDIS_PORT
    env_file:
      - ../../.env      

  web:
    build: ../..
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host=0.0.0.0"
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ../../admin:/app/admin
    env_file:
      - ../../.env

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - ../../.env
    ports:
      - $RABBITMQ_PORT:$RABBITMQ_PORT

  flower:
    image: mher/flower
    #environment:  left for memory:)
    #  - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    ports:  # examples of good practices:)
      - ${FLOWER_PORT:-5555}:${FLOWER_PORT:?error}
    depends_on:
      - rabbitmq
    env_file:
      - ../../.env        

  celery_worker:
    build: ../..
    # command: bash -c "celery -A app.tasks beat && celery -A app.tasks worker --loglevel=debug"
    command: bash -c "celery -A app.tasks worker -B --loglevel=debug"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      - web
    env_file:
      - ../../.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  menus_data:
