services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - menus_data:/var/lib/postgresql/data/
    env_file:
      - ../../.env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  web:
    build: ../..
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - ../../.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
    ports:
      - '8000:8000'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  menus_data:
